### generate token

POST http://localhost:6000/generatetoken/publisher?userId=32 HTTP/1.1
Content-Type: application/json

{   
    "ttl": 15,
    "resources": {
        "channels": {
            "channel-a": {
                "read": true
            },
            "channel-b": {
                "read": true,
                "write": true
            },
            "channel-c": {
                "read": true,
                "write": true
            },
            "channel-d": {
                "read": true,
                "write": true
            }
        },
        "uuids": {
            "uuid-c": {
                "get": true
            },
            "uuid-d": {
                "get": true,
                "update": true
            }
        }
    }
}

### getToken 
GET http://localhost:6000/getToken/publisher HTTP/1.1